steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/activelearning-308016/github.com/s0tt/label-studio', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/activelearning-308016/github.com/s0tt/label-studio']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'label-studio-al-project-01', '--image', 'gcr.io/activelearning-308016/github.com/s0tt/label-studio', '--region', 'REGION', '--platform', 'managed']
images:
- gcr.io/activelearning-308016/github.com/s0tt/label-studio
